// Codes/employee-angular-app/src/app/add-employee/add-employee.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Employee } from '../employee';
import { EmployeeService } from '../employee.service';

@Component({
  selector: 'app-add-employee',
  templateUrl: './add-employee.component.html',
  styleUrls: ['./add-employee.component.css'],
})
export class AddEmployeeComponent implements OnInit {
  constructor(
    private employeeService: EmployeeService,
    private route: Router
  ) {}

  employee: Employee = new Employee();

  ngOnInit(): void {}

  addFormSumbit() {
    console.log(JSON.stringify(this.employee));

    //=====> 1. Calling SpringBoot Save Service method
    this.employeeService.createEmployee(this.employee).subscribe(
      (data) => {
        console.log('Data Saved : ' + data);
      },
      (error) => {
        console.log('Save failed  : ' + error);
      }
    );

    //=====>2. Once Save Done, Reditect to employeeList page
    this.route.navigate(['/all']);
  }
}

<div class="card">
  <div class="card-body">
    <div class="col-10 mx-auto">
      <h2 class="text-center">Add Employee</h2>
      <!-- <p> {{employeeList[0].name}}</p> -->
    </div>
    <br />
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
        <form (ngSubmit)="addFormSumbit()" data-toggle="validator">

          <div class="row mb-3">
            <label for="name" class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="name" required [(ngModel)]="employee.name" name="name">
            </div>
          </div>

          <div class="row mb-3">
            <label for="address" class="col-sm-2 col-form-label">Address</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="address" required [(ngModel)]="employee.address" />
            </div>
          </div>

          <div class="row mb-3">
            <label for="salary" class="col-sm-2 col-form-label">Salary</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="salary" required [(ngModel)]="employee.salary"/>
            </div>
          </div>
          <div class="row mb-3">
            <label for="salary" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-8">
              <button type="submit" class="btn btn-primary">Add Employee</button> &nbsp;
              <button type="button" class="btn btn-danger" onclick="this.form.reset();">Clear</button>
            </div>
          </div>

        </form>
      </div>
      <div class="col-md-3"></div>
    </div>
  </div>

// Codes/employee-react-app/src/component/AddEmployeeComponent.jsx
import React, { Component } from 'react';
import EmployeeService from '../services/EmployeeService';

class AddEmployeeComponent extends Component {


    constructor(props) {
        super(props);
        this.state = {
            name: '',
            address: '',
            salary: 0
        };

        this.changeNameHandler = this.changeNameHandler.bind(this);
        this.changeAddressHandler = this.changeAddressHandler.bind(this);
        this.changeSalaryHandler = this.changeSalaryHandler.bind(this);
    }


    changeNameHandler= (event) => {
        this.setState({name: event.target.value});
    }

    changeAddressHandler= (event) => {
        this.setState({address: event.target.value});
    }

    changeSalaryHandler= (event) => {
        this.setState({salary: event.target.value});
    }


    saveEmployee = (e) =>{
        e.preventDefault();
        let employee = {
            name: this.state.name, 
            address: this.state.address, 
            salary: this.state.salary
        };
        console.log('employee => ' + JSON.stringify(employee));

        EmployeeService.addEmployee(employee).then(res =>{
            this.props.history.push('/all');
        });

        
    }







    render() {
        return (
            <div>
                <br />
                <h2 className="text-center">Add Employee </h2>

                <br></br>
                <div className="row">
                    <div className="col-md-3"></div>
                    <div className="col-md-6">
                        <form>

                            <div class="row mb-3">
                                <label for="name" class="col-sm-2 col-form-label">Name</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="name" value={this.state.name} onChange={this.changeNameHandler}/>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="address" class="col-sm-2 col-form-label">Address</label>
                                <div class="col-sm-10">
                                <input type="text" class="form-control" name="address" value={this.state.address} onChange={this.changeAddressHandler}/>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="salary" class="col-sm-2 col-form-label">Salary</label>
                                <div class="col-sm-10">
                                <input type="text" class="form-control" name="salary" value={this.state.salary} onChange={this.changeSalaryHandler}/>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="salary" class="col-sm-2 col-form-label"></label>
                                <div class="col-sm-8">
                                    <button type="button" class="btn btn-primary" onClick={this.saveEmployee.bind(this)}>Add Employee</button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        );
    }
}

export default AddEmployeeComponent;
