// Codes/employee-react-app/src/component/ViewEmployeeComponent.jsx
import React, { Component } from 'react';
import EmployeeService from '../services/EmployeeService';

class ViewEmployeeComponent extends Component {


    constructor(props) {
        super(props);
        this.state = {
            id: this.props.match.params.id,
            name: '',
            address: '',
            salary: 0
        };
    }




    componentDidMount() {
        EmployeeService.getEmployeeById(this.state.id).then((res) => {
            let employee = res.data;
            console.log("employee ::: " + employee);
            this.setState({
                name: employee.name,
                salary: employee.salary,
                address: employee.address
            });
        });
    }


    render() {
        return (
            <div>
                <br />
                <h2 className="text-center">View Employee ::</h2>

                <br></br>
                <div class="card">
                    <div class="card-body">
                    <div class="shadow-lg p-3 mb-5 bg-body rounded">
                        Id : {this.state.id}         <br/>
                        Name : {this.state.name}     <br/>
                        Address : {this.state.address}   <br/>
                        Salary : {this.state.salary}     <br/>
                    </div>
                    </div>
                </div>
            </div>
        );
    }
}

export default ViewEmployeeComponent;

// Codes/employee-angular-app/src/app/view-employee/view-employee.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Employee } from '../employee';
import { EmployeeService } from '../employee.service';

@Component({
  selector: 'app-view-employee',
  templateUrl: './view-employee.component.html',
  styleUrls: ['./view-employee.component.css']
})
export class ViewEmployeeComponent implements OnInit {

  constructor(
    private employeeService: EmployeeService,
    private route: Router,
    private activatedRoute : ActivatedRoute
  ) {}

  id!: number;
  employee: Employee = new Employee();

  ngOnInit(): void {
    this.id = this.activatedRoute.snapshot.params['id'];
    this.employeeService.getEmployeeById(this.id).subscribe(data =>{
      this.employee = data;
    });
  }

}

<div class="card">
  <div class="card-body">
    <div class="col-10 mx-auto">
      <h2 class="text-center">View Employee</h2>
      <!-- <p> {{employeeList[0].name}}</p> -->
    </div>
    <br />
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">


          <div class="row mb-3">
            <label for="name" class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="name" required [(ngModel)]="employee.name" name="name" disabled>
            </div>
          </div>

          <div class="row mb-3">
            <label for="address" class="col-sm-2 col-form-label">Address</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="address" required [(ngModel)]="employee.address" disabled />
            </div>
          </div>

          <div class="row mb-3">
            <label for="salary" class="col-sm-2 col-form-label">Salary</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="salary" required [(ngModel)]="employee.salary" disabled/>
            </div>
          </div>

      </div>
      <div class="col-md-3"></div>
    </div>
  </div>
